apiVersion: v1
kind: Service
metadata:
  name: znc
  labels:
    app: znc
spec:
  selector:
    app: znc
  type: NodePort
  ports:
    - name: znc
      port: 6667
      nodePort: 30001
      protocol: TCP
